apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-pv
  namespace: zookeeper-kafka
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/zookeeper/data
