apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: zookeeper-kafka
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      protocol: TCP
      targetPort: http-zookeeper
