apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: zookeeper-kafka
spec:
  ports:
    - port: 8081
      targetPort: http-outport
      protocol: TCP
  selector:
    app: schema-registry
