apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
  namespace: zookeeper-kafka
spec:
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
              name: http-kui
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/kafkaui
              name: kafkaui-config
      volumes:
        - name: kafkaui-config
          configMap:
            name: kafkaui-config
