apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: zookeeper-kafka
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http-kui
  selector:
    app: kafka-ui
  type: LoadBalancer
