apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: zookeeper-kafka
spec:
  ports:
    - name: external
      port: 9092
      protocol: TCP
      targetPort: http-external
    - name: internal
      port: 29092
      protocol: TCP
      targetPort: http-internal
  selector:
    app: kafka
  type: LoadBalancer
